version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: '*'
    update-types: ['version-update:semver-patch']
  - dependency-name: axios-mock-adapter
    versions:
    - "> 1.18.1, < 1.19"
  - dependency-name: "@babel/core"
    versions:
    - "> 7.11.0, < 7.12"
  - dependency-name: cypress
    versions:
    - "> 4.12.0, < 4.13"
  - dependency-name: eslint-plugin-react
    versions:
    - "> 7.20.3, < 7.21"
  - dependency-name: husky
    versions:
    - "> 5.1.1, < 5.2"
  - dependency-name: react-redux
    versions:
    - "> 7.2.0, < 7.3"
  - dependency-name: single-spa
    versions:
    - "> 5.5.4, < 5.6"
  - dependency-name: single-spa
    versions:
    - "> 5.9.1, < 5.10"
  - dependency-name: "@storybook/addon-links"
    versions:
    - "> 6.1.20, < 6.2"
  - dependency-name: "@storybook/addons"
    versions:
    - "> 6.1.20, < 6.2"
  - dependency-name: "@storybook/react"
    versions:
    - "> 6.1.20, < 6.2"
  - dependency-name: typescript
    versions:
    - "> 3.9.6, < 3.10"
  - dependency-name: typescript
    versions:
    - "> 4.2.2, < 4.3"
  - dependency-name: "@types/history"
    versions:
    - "> 4.7.3, < 4.8"
  - dependency-name: "@types/jest"
    versions:
    - "> 26.0.4, < 26.1"
  - dependency-name: "@types/jsonwebtoken"
    versions:
    - "> 8.5.0, < 8.6"
  - dependency-name: "@types/node"
    versions:
    - "> 14.0.20, < 14.1"
  - dependency-name: "@types/react"
    versions:
    - "> 16.9.43, < 16.10"
  - dependency-name: "@types/react"
    versions:
    - "> 17.0.2, < 17.1"
  - dependency-name: "@types/react-dom"
    versions:
    - "> 17.0.1, < 17.1"
  - dependency-name: webpack
    versions:
    - ">= 5.a, < 6"
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
    - 7.2.0
    - 8.0.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.29
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.4.0
    - 5.5.0
    - 5.6.0
    - 5.7.0
    - 5.7.1
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: cypress
    versions:
    - 6.7.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
