name: CI Build
on:
  pull_request:
  # By default, the pull_request event type is not triggered when a PR is merged into main
  push:
    # TODO - Change this to main before merging k8s-deployment into main
    branches:
      - k8s-deployment

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # Cache yarn dependencies/ restore the cached dependencies during future workflows
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        # Ubuntu 16+ does not install libgconf-2-4 by default, so we need to install it ourselves (for Cypress)
        run: |
          npm config set scripts-prepend-node-path true
          sudo apt-get install libgconf-2-4
          yarn --frozen-lockfile
      - name: Run linting
        run: yarn lint:js
      - name: Run unit tests
        run: yarn test
      - name: Upload unit test coverage
        if: success()
        uses: codecov/codecov-action@v1
      - name: Run e2e tests
        run: yarn e2e

  docker:
    # This job triggers only if all the other jobs succeed and does different things depending on the context.
    # The job builds the Docker image in all cases and also pushes the image to Harbor only if something is
    # pushed to the k8s-deployment branch.
    needs: [test]
    name: Docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.stfc.ac.uk/datagateway
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: harbor.stfc.ac.uk/datagateway/scigateway

      # TODO - Change github.ref to refs/heads/main before merging k8s-deployment into main
      - name: ${{ github.event_name == 'push' && github.ref == 'refs/heads/k8s-deployment' && 'Build and push Docker image to Harbor' || 'Build Docker image' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          # TODO - Change github.ref to refs/heads/main before merging k8s-deployment into main
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/k8s-deployment' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
