name: Build & Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - deployment/push-docker-image-to-harbor-#1030

jobs:
  push_to_registry:
    name: Push Docker image to Harbor
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
