name: Build & Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - deployment/push-docker-image-to-harbor-#1030

jobs:
  push_to_registry:
    name: Push Docker image to Harbor
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.stfc.ac.uk/datagateway
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: harbor.stfc.ac.uk/datagateway/scigateway
