name: Prepare Release
on:
  push:
    branches:
      - 'release/v?[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    # only run when branch is first created
    if: github.event.created == true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Strip release prefix
        run: echo "VERSION=$(echo ${BRANCH_NAME#release/})" >> $GITHUB_ENV

      - name: Get version number
        run: echo "VERSION=$(echo ${VERSION#v})" >> $GITHUB_ENV

      - name: Bump version number
        run: yarn version --new-version $VERSION --no-git-tag-version

      - name: 'Generate changelog'
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: CHANGELOG-BASE.md
          excludeTags: 'snapshot,snapshot-develop'
          futureRelease: v${{ env.VERSION }}

      - name: Commit changelog & package.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG and version for v${{ env.VERSION }}
          file_pattern: CHANGELOG.md package.json
