name: Prepare Release
on:
  push:
    branches:
      - 'release/v?[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    # only run when branch is first created
    if: github.event.created == true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Get version number
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "VERSION=$(echo ${GITHUB_REF#v})" >> $GITHUB_ENV

      - name: Bump version numbers
        run: yarn version --new-version $VERSION

      - name: 'Generate changelog'
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: CHANGELOG-BASE.md
          excludeTags: 'snapshot,snapshot-develop'

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
